### ISSUE TITLE
Demo Mode

### ISSUE THREAD

**Issue by NewMan787** [acebusters/acebusters-frontend#932]
hi, is it possible to run the application in demo mode ?

**Comment by sunify** [comment]
What do you mean?

**Comment by NewMan787** [comment]
I started the application but all the time returning;

"WebSocket connection to 'wss: //rinkeby3.acebusters.com/' failed: Error in connection establishment: net :: ERR_NAME_NOT_RESOLVED '

Any idea ? 

Is it possible to add some bots in one place and go directly to the game view ?

Thanks!

**Comment by sunify** [comment]
`"WebSocket connection to 'wss: //rinkeby3.acebusters.com/'`

It was our ethereum node and It's not working anymore.

Anyway, besides the geth node you need to deploy contracts and setup the whole backend to run this app.

**Comment by NewMan787** [comment]
Are you able to help me with that ?

**Comment by sunify** [comment]
I have no interest in this. It may take a lot of time

--
Alexander Lunyov
https://sunify.github.io
